In [2]:
import torch 
import numpy as np


In [3]:
VECTOR = torch.tensor([1,2,4])
print(VECTOR.ndim)
print(VECTOR.shape)

1
torch.Size([3])


### `torch.tensor always copies the input `

In [4]:
TENSOR = torch.tensor([[2,5,5]])
print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([1, 3])
2


### Random Tensors

In [5]:
random_tensors = torch.rand(3,4)
print(random_tensors.ndim)
random_tensors

2


tensor([[0.2550, 0.0744, 0.8124, 0.1587],
        [0.2818, 0.5873, 0.6166, 0.0604],
        [0.1798, 0.6956, 0.3319, 0.2347]])

In [6]:
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)} is available.")
else:
    print("No GPU available. Training will run on CPU.")

No GPU available. Training will run on CPU.


In [7]:
ones = torch.ones(size = (3,5) , dtype = torch.int64)
zeros = torch.zeros(size = (4,5) , dtype = torch.float64)

print(zeros.dtype)
print(ones.dtype)

torch.float64
torch.int64


## Creating range tensors

In [8]:
tensors_range = torch.arange(start = 1 , end = 5, step = 2)

tensors_like_range = torch.zeros(size = tensors_range.shape , dtype = tensors_range.dtype , layout=  tensors_range.layout)

#alternate function 
zeros_like_range = torch.zeros_like(tensors_range)
tensors_like_range.shape
zeros_like_range.shape

torch.Size([2])

### Pytorch Data Types

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

if you try to compute 2 tensors which are on different device, there will be an error

In [9]:
float_64_tensor = torch.tensor([3 , 5, 9] , dtype = torch.double , 
                               device = None , 
                               requires_grad=  True)
float_64_tensor.dtype
float_64_tensor


tensor([3., 5., 9.], dtype=torch.float64, requires_grad=True)

In [10]:
float16_tensor = float_64_tensor.type(torch.half)
float16_tensor.dtype
# float_64_tensor.shape

# default is torch.float32 or torch.float

torch.float16

tensor.size() and tensor.shape 
tensor.size() is a function or method 
tensor.shape is an attribute

In [11]:
float16_tensor.device

device(type='cpu')

### Matrix multiplication

torch.mm - performs a matrix multiplication without broadcasting - (2D tensor) by (2D tensor) \
torch.mul - performs a elementwise multiplication with broadcasting - (Tensor) by (Tensor or Number) \
torch.matmul - matrix product with broadcasting - (Tensor) by (Tensor) with different behaviors depending on the tensor shapes (dot product, matrix product, batched matrix products 

In [13]:
float16_tensor = torch.ShortTensor([1,2,3])
int16_tensor = torch.IntTensor([1,2,3])
int16_tensor
float16_tensor

tensor([1, 2, 3], dtype=torch.int16)

Data type                                           CPU tensor                                                          GPU tensor \

32-bit floating point                           torch.FloatTensor                                                     torch.cuda.FloatTensor

64-bit floating point                           torch.DoubleTensor                                                    torch.cuda.DoubleTensor

16-bit floating point                           torch.HalfTensor                                                       torch.cuda.HalfTensor

16-bit floating point                           torch.BFloat16Tensor                                                    torch.cuda.BFloat16Tensor

8-bit integer (unsigned)                        torch.ByteTensor                                                         torch.cuda.ByteTensor



### `torch.max(input, dim , keepdims , * , out = None) -> Tensor`

In [14]:
x = torch.arange(1,101,10)

torch.min(x)
x.min()

tensor(1)

### `torch.mean(input , dim, keepdims, *,  dtype = None , out = None) ->Tensor `

In [15]:

torch.mean(x.type(torch.double))

tensor(46., dtype=torch.float64)

torch.mean(x) \
throws error

common programming courtesy :\
dont expect the output data type to be different from the input's 

In [16]:
torch.mean(x , dtype = torch.half)

tensor(46., dtype=torch.float16)

In [17]:
torch.sum(x)

tensor(460)

### `torch.sum(input, *, dtype=None) → Tensor`

`input (Tensor) `– the input tensor. 

`dim` (int or tuple of ints, optional) – the dimension or 
dimensions to reduce. If None, all dimensions are reduced.  

`keepdim (bool)` – whether the output tensor has dim retained or  not. 

`dtype (torch.dtype, optional) `– the desired data type of returned tensor. If specified, the input tensor is casted to dtype before the operation is performed. This is useful for preventing data type overflows. Default: None



### `torch.argmax(input) → LongTensor `
Returns the indices of the maximum value of all elements in the input tensor.

In [18]:
a = torch.randn(4, 4)
a

tensor([[-0.7319,  0.0813,  0.5135,  1.3430],
        [-0.6131, -0.3220, -0.1060,  0.0666],
        [ 1.1868,  1.5562,  1.6909, -0.6307],
        [ 0.0967, -0.0808, -0.9787,  1.2553]])

### `input (Tensor) – the input tensor. `

`dim (int) `– the dimension to reduce. If None, the argmax of the flattened input is returned.

`keepdim (bool)` – whether the output tensor has dim retained or not.

In [19]:

torch.argmax(a, dim=1)

tensor([3, 3, 2, 3])

In [20]:
torch.argmax(a, dim = 0 , keepdims = True)

tensor([[2, 2, 2, 0]])

### `torch.reshape(input, shape) → Tensor`
Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.

See `torch.Tensor.view()` on when it is possible to return a view. which will throw an error if the operation cannot be done without copying the data.

### `torch.stack(tensors, dim=0, *, out=None) → Tensor`
Concatenates a sequence of tensors along a new dimension.

All tensors need to be of the same size.

In [31]:
x = torch.randn(3,4)
y = torch.randn(2,4)


# x and y stack not possible

xx = torch.stack((x, x), dim = 0)
x2 = torch.stack((x,x) , dim = 1)
x3 = torch.stack((x,x) , dim = 2)
xx.shape , x2.shape , x3.shape


(torch.Size([2, 3, 4]), torch.Size([3, 2, 4]), torch.Size([3, 4, 2]))

In [29]:


xcat = torch.cat((x,x), dim = 0)
ycat = torch.cat((x,x), dim = 1)
xcat.shape , ycat.shape

(torch.Size([6, 4]), torch.Size([3, 8]))

### `torch.squeeze(input, dim)`

Returns a tensor with all specified dimensions of input of size 1 removed.

For example, if input is of shape: 
(
A
×
1
×
B
×
C
×
1
×
D
)
(A×1×B×C×1×D) then the input.squeeze() will be of shape: 
(
A
×
B
×
C
×
D
)
(A×B×C×D).

When dim is given, a squeeze operation is done only in the given dimension(s). If input is of shape: 
(
A
×
1
×
B
)
(A×1×B), squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape 
(
A
×
B
)
(A×B).

dim also accepts tuple of dimensions

If the tensor has a batch dimension of size 1, then squeeze(input) will also remove the batch dimension, which can lead to unexpected errors. Consider specifying only the dims you wish to be squeezed

### `torch.unsqueeze(input, dim)`
Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1

### ` torch.permute(torch.permute(input, dims) → Tensor `
Returns a view of the original tensor input with its dimensions permuted.

Parameters
input (Tensor) – the input tensor.

dims (tuple of int) – The desired ordering of dimensions)


### same as nuumpy.transpose(input, axes = ())  😔

### `torch.from_numpy(ndarray) → Tensor`
Creates a Tensor from a numpy.ndarray.

The returned tensor and ndarray share the same memory. Modifications to the tensor will be reflected in the ndarray and vice versa. The returned tensor is not resizable.

tensor default dtype is Tensor.float32 and numpy default dtype is np.float64

In [35]:
random_seed = 4
torch.manual_seed(random_seed)

tensora = torch.randn(3,3)

torch.manual_seed(random_seed)
tensorc = torch.randn(3,3)


if((tensora == tensorc)).all():
    print("same tensors")

else :
    print("different tensors")


same tensors


### `Strided Tensor`
1. Memory Layout: A strided tensor is the default dense tensor in PyTorch. The data is stored in a contiguous block of memory, but the way elements are accessed is controlled by the stride of the tensor.
2. Strides: Strides are a set of integers that indicate the number of memory locations to skip to move to the next element along each dimension. For example, if a 2D tensor has a shape of (3, 4) and strides (4, 1), it means that moving one step along the first dimension (rows) involves skipping 4 memory locations, while moving along the second dimension (columns) involves skipping 1 location.
3. Efficiency: Strided tensors are efficient for most operations since they provide direct access to the elements in memory.
Reshape and View: Operations like torch.reshape and torch.view work well with strided tensors, especially if the tensor is contiguous (i.e., the strides are such that the tensor elements are stored sequentially in memory).
### `Sparse Tensor`
1 .Memory Layout: A sparse tensor is used to efficiently store and operate on tensors that have a large number of zero elements. Instead of storing all elements, only the non-zero elements and their locations are stored. \
2. Storage: Sparse tensors are usually represented using two main components: \
        -Indices: A tensor that stores the indices of the non-zero elements. \
        -Values: A tensor that stores the values of the non-zero elements.

### `torch.view() `
In PyTorch and NumPy, a "view" of a tensor or array is a way of accessing the same underlying data in memory with a different shape or stride configuration. Here's how it works:

1. Understanding Views
A view is a new tensor (or array) that shares the same data as the original tensor but might have a different shape, stride, or order of elements.

2. Memory Layout and Strides
Memory Layout: Tensors and arrays are stored in contiguous blocks of memory. For example, in a 2D tensor, elements are laid out row by row in memory (this is called "row-major order" or "C-style" ordering).

Strides: Strides define how many steps in memory you need to take to move from one element to the next along each dimension. For example, in a 2D tensor with shape (3, 4), the stride could be (4, 1), meaning to move along the first dimension (rows), you move 4 steps in memory, and to move along the second dimension (columns), you move 1 step in memory.

3. Creating Views
When you create a view, you're essentially telling the system to interpret the existing data differently without copying it. For example, you might reshape a tensor from (6,) to (2, 3). The new shape and strides allow you to index the same data differently.


4. Memory Efficiency
Since views do not involve copying data, they are memory-efficient. Instead of allocating new memory, the view tensor just reinterprets the memory layout of the original tensor.
5. `Contiguity`
` A tensor is "contiguous" if its elements are stored in a contiguous block of memory. Operations like reshaping often result in contiguous tensors, but some operations may result in non-contiguous tensors. If a tensor is not contiguous, some operations may require making it contiguous first, which involves copying the data.`


`contiguous()` returns itself if input tensor is already contiguous, otherwise it returns a new contiguous tensor by copying data.

In [42]:
tensor = torch.randn(3,4)

print(f"tensor is contiguous : {tensor.is_contiguous()}")

tensort = tensor.T

print(f"transpose tensor is contiguous : {tensort.is_contiguous()}")

print(tensort)

reshaped_tensor  = torch.reshape(tensort , (4,3))

print(f"reshaped tensor is contiguous : {reshaped_tensor.is_contiguous()}")

contiguous_reshaped_tensor = torch.Tensor.contiguous(reshaped_tensor)

# contiguous_reshaped_tensor = reshaped_tensor.contiguous()        it is an attribute of the object

print(f"the contiguos reshaped tensor is continguos : {contiguous_reshaped_tensor.is_contiguous()}")

print(reshaped_tensor.shape)




tensor is contiguous : True
transpose tensor is contiguous : False
tensor([[ 1.3055, -2.1691, -0.2993],
        [ 0.1070,  0.4707,  0.9054],
        [-0.1010, -0.4063, -0.9879],
        [-0.3921,  2.2503, -0.3762]])
reshaped tensor is contiguous : False
the contiguos reshaped tensor is continguos : True
torch.Size([4, 3])


### `torch.transpose(input, dim0, dim1) → Tensor `
Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

If input is a strided tensor then the resulting out tensor shares its underlying storage with the input tensor, so changing the content of one would change the content of the other.

If input is a sparse tensor then the resulting out tensor does not share the underlying storage with the input tensor.